version: "3.7"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
  #react:
  #  build: react
  #  ports:
  #    - "80:80"
  gotty-host:
    build: gotty
    command: gotty -p 80 -w ssh gns3@192.168.1.1
  gotty-so-master:
    build: gotty
    command: gotty -p 80 -w ssh -J gns3@192.168.1.1 so-user@192.168.0.11

networks:
  so-manager:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
