version: "3.7"

services:
  # Public service
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - so-vm-proxy
      - so-manager-proxy
      - thehive-proxy-thehive
      - thehive-proxy-cortex
      - ntop-proxy
    restart: always
    environment:
      WEBSOCKET: 'true'
      DOMAINS: '
        ${HTTP_BASIC_AUTH}@sopoc.duckdns.org -> http://so-manager-proxy,
        so-sopoc.duckdns.org -> http://so-vm-proxy,
        thehive-sopoc.duckdns.org -> http://thehive-proxy-thehive,
        cortex-sopoc.duckdns.org -> http://thehive-proxy-cortex,
        ${HTTP_BASIC_AUTH}@ntopng-sopoc.duckdns.org -> http://ntop-proxy
      '

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
