version: "3.7"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    networks:
      - so-manager
  #react:
  #  build: react
  #  ports:
  #    - "80:80"
  #  networks:
  #    - so-manager
  gotty-host:
    build: gotty
    command: gotty -p 80 -w ssh 192.168.100.1
    networks:
      - so-manager
  gotty-so-master:
    build: gotty
    command: gotty -p 80 -w ssh -J 192.168.100.1 so-user@192.168.101.2
    networks:
      - so-manager

networks:
  so-manager:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
