version: "3.7"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    networks:
      - so-manager
  #react:
  #  build: react
  #  ports:
  #    - "80:80"
  #  networks:
  #    - so-manager
  gotty-host:
    build: gotty
    command: gotty -w -a 192.168.1.30 ssh gns3@192.168.1.1
    ports:
      - "8001:8080"
    networks:
      - so-manager
  gotty-so-master:
    build: gotty
    command: gotty -w -a 192.168.1.31 ssh -J gns3@192.168.1.1 so-user@192.168.0.11
    ports:
      - "8011:8080"
    networks:
      - so-manager

networks:
  so-manager:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
