version: "3.7"

# Misp instance
# https://github.com/MISP/misp-docker/blob/master/docker-compose.yml

services:
  misp-proxy:
    build: misp/misp-proxy
    depends_on:
      - misp-web
    ports:
      - ${SO_GATEWAY}:6000:80
  misp-web:
    build: misp/web
    depends_on:
      - misp-db
    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
    environment:
      - MYSQL_HOST=misp-db
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=misp
      - MISP_ADMIN_EMAIL=${AUTH_USER}@${MISP_HOSTNAME}
      - MISP_ADMIN_PASSPHRASE=${AUTH_PASS}
      - MISP_BASEURL=${MISP_HOSTNAME}
      - POSTFIX_RELAY_HOST=
      - TIMEZONE=Europe/Brussels
  misp-db:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD=misp
      - MYSQL_ROOT_PASSWORD=misp
