version: "3.7"

services:
  # Public service
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - so-vm-proxy
      - so-manager-proxy
    restart: always
    environment:
      DOMAINS: '
        jonas:L0gMeIn@sopoc.duckdns.org -> http://so-manager-proxy,
        so-sopoc.duckdns.org -> http://so-vm-proxy
      '
      WEBSOCKET: "true"
    networks:
      - so-manager

  # Security Onion
  so-vm-proxy:
    build: so-vm-proxy
    networks:
      - so-manager

  # Management web application
  so-manager-proxy:
    build: so-manager-proxy
    networks:
      - so-manager
  react:
    build: react
    networks:
      - so-manager
  gotty-host:
    build: gotty
    command: gotty -p 80 -w ssh debian@192.168.100.1
    networks:
      - so-manager
  gotty-so:
    build: gotty
    command: gotty -p 80 -w ssh -J debian@192.168.100.1 so-user@192.168.101.2
    networks:
      - so-manager

networks:
  so-manager:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
