version: "3.7"

services:
  # Public service
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - so-vm-proxy
      - so-manager-proxy
      - thehive-proxy-thehive
      - thehive-proxy-cortex
      - ntop-proxy
      - netdata-proxy
      - misp-proxy
    restart: always
    environment:
      WEBSOCKET: 'true'
      DOMAINS: '
        ${AUTH_USER}:${AUTH_PASS}@sopoc.duckdns.org -> http://so-manager-proxy,
        so-sopoc.duckdns.org -> http://so-vm-proxy,
        thehive-sopoc.duckdns.org -> http://thehive-proxy-thehive,
        cortex-sopoc.duckdns.org -> http://thehive-proxy-cortex,
        ${AUTH_USER}:${AUTH_PASS}@ntopng-sopoc.duckdns.org -> http://ntop-proxy,
        ${AUTH_USER}:${AUTH_PASS}@netdata-sopoc.duckdns.org -> http://netdata-proxy,
        misp-sopoc.duckdns.org -> http://misp-proxy
      '

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
